#!/usr/sbin/nft -f

flush ruleset

table ip filter {
	chain input {
		type filter hook input priority 0;

		# Default policy
		policy drop;

		# Allow loopback
		iif lo accept

		# Allow established connections
		ct state established,related accept

		# Allow HTTP
		tcp dport 80 accept

		# Drop SSH (remote access)
		tcp dport 22 drop

		# Block Direct Access to Flask app  (for project testing)
		tcp dport 5000 drop

		# Allow ICMP
		ip protocol icmp accept

		# Log dropped packets
		log prefix "FIREWALL DROP: "
	}

	chain forward {
		type filter hook forward priority 0;
		policy drop;
	}

	chain output {
		type filter hook output priority 0;
		policy accept;
	}
}
