## modsecurity engine configuration
Include /etc/nginx/modsec/modsecurity.conf

## setup configuration for OWASP CRS
Include /etc/nginx/modsec/coreruleset/crs-setup.conf

## All actual detection rule
Include /etc/nginx/modsec/coreruleset/rules/*.conf
